name: Eslint
run-name: ${{ github.actor }} is running GitHub Actions 🚀

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    linter:
        name: Run ESLint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install dependencies
              run: yarn install

            - name: Run linter
              run: yarn lint
