name: Tests
run-name: ${{ github.actor }} is running GitHub Actions 🚀

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    tests:
        name: Run Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install dependencies
              run: yarn install

            - name: Run tests with coverage
              run: yarn test --coverage
